spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anthea?serverTimezone=UTC
    username: root
    password: sxn700320
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-DD HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.example.domain
  mapper-locations: classpath:mapper/*.xml
